# Generated by Django 4.0.3 on 2022-07-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_products_description_alter_products_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
