# Generated by Django 4.0.6 on 2022-07-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
