# Generated by Django 4.0.6 on 2022-07-19 18:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
