# Generated by Django 4.0.6 on 2022-07-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_catagory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='slug',
        ),
    ]
