# Generated by Django 4.0.6 on 2022-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_catagory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
